### PR TITLE
setHeightToRenderWholePage() width issue

### PR DESCRIPTION
**Pull request by c2pdev**
Fix width issue when setHeightToRenderWholePage

### CODE REVIEW

**Comment by freekmurze** [comment]
The automated tests report syntax errors in this PR. Could you make sure the submitted code is correct and works?

**Comment by c2pdev** [comment]
I've fixed the issue and tests are comming fine now

**Comment by freekmurze** [comment]
Correct me if I'm wrong but it seems to me that this PR sets the height to 1 pixel when not specifying a height. Wouldn't this produce a image with a height of only one pixel?

**Comment by c2pdev** [comment]
It may look weird but it works properly. If the height is set image will be rendered with  a proper value. If we don't set height it will use default value (480px). And most of all full width screenshot is rendered correctly.

**Comment by c2pdev** [comment]
It looks like a bug in PhantomJS that ignores declared width if the height is  set to 0

**Comment by freekmurze** [comment]
Ok, trusting you on this one!

Thanks for this PR

**Pull request merged**
