### PR TITLE
Hotfix/readme update

### PR DESCRIPTION
**Pull request by MJunaidAhmad**
I have added the example of format method available for generating pdf and added available option to pass on to format method. Because there was an open issue regarding this method. (issue no. #325)

### CODE REVIEW

**Comment by freekmurze** [comment]
Hi,

thank you for this PR! Unfortunately I can't merge this in it's current state. On https://github.com/spatie/browsershot/pull/336/files you'll see that your editor made, probably without your knowledge, many whitespace changes and newlines. This makes it hard for me to see the actual changes.

Could you fix this PR (or submit a new one) with only your intended change?

Thank you!

**Comment by MJunaidAhmad** [comment]
oh, I didn't notice that. Sorry for the mistake. Will submit a new PR. 
Thanks!

**Comment by freekmurze** [comment]
No apologies necessary, thank you for your work!

**Comment by MJunaidAhmad** [comment]
I am about to submit a new PR. 
And this time I am reviewing the changes prior to submission.
All the formating issues are resolved but I am unable to resolve this last one (see the attached screenshot) neither can figure it out what's the problem because both lines are same. 
Shall I submit the PR?
browsershot

**Comment by freekmurze** [comment]
Submit it and I'll take another look.

**Comment by MJunaidAhmad** [comment]
Done.

**Pull request closed without merging**
