### PR TITLE
sandbox option

### PR DESCRIPTION
**Pull request by sPooKee**
Now u can disable sandbox mode, when u'r running on a docker container.

### CODE REVIEW

**Comment by freekmurze** [comment]
What is sandbox mode?

Could you also add a test and add an example of the new function to the readme?

**Comment by sPooKee** [comment]
I tried to run this lib in a docker container and got the following error:

`Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted`

After adding a `--no-sandbox` argument to the command, it worked.

I found this in Issue: https://github.com/jessfraz/dockerfiles/issues/65

**Comment by freekmurze** [comment]
Could you add a test to prove that this works?

**Comment by freekmurze** [comment]
Reopen when tests have been added.

**Pull request closed without merging**
