### PR TITLE
Add extraHTTPHeaders options

### LINKED ISSUE #171: Send custom header
For our use case we need to send an authorization header with our request. I can't find a way to support this here. Is it an option?

### PR DESCRIPTION
**Pull request by artggd**
Hi,
This PR allows to add HTTP headers to the page call using [extraHTTPHeaders](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetextrahttpheadersheaders) option. Fixes #171

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks! Could you also update the readme and add a test?

**Comment by artggd** [comment]
I added a test and updated the readme 🙂

**Comment by freekmurze** [comment]
Great, thanks!

**Comment by ChrisWiegman** [comment]
Thanks for addressing #171 so quickly, particularly as it was more than just something I missed in the docs somewhere.

**Comment by artggd** [comment]
All good mate, I needed this feature on my use case 🙂

**Pull request merged**
