### PR TITLE
Workaround escaping problem on Windows by putting command into tempor…

### PR DESCRIPTION
**Pull request by paulrrogers**
…ary file.

Resolve https://github.com/spatie/browsershot/issues/409 by putting command into a temporary file

### CODE REVIEW

**Comment by freekmurze** [comment]
Having to create a file for this feels like a "heavy" solution. Is there no way to do this without having to write something to the filesystem?

**Comment by paulrrogers** [comment]
@freekmurze I agree this is hacky but couldn't find any other way after trying 10 different ways. Perhaps someone with deeper knowledge of the Microsoft command line and Node escaping could find a solution, though it may require changes in those dependencies.

**Comment by freekmurze** [comment]
Please fork the package and use your solution there. I hope your understand that I don't want to maintain the hacky solution.

Thanks for your work on this though.

**Comment by paulrrogers** [comment]
@freekmurze I understand. Thanks for your consideration. If it's not too much trouble please mark the PR as hacktoberfest-accepted.

@waleedmazhar you're free to use this PR in a fork if you like. I don't plan on maintaining a fork for my purposes.

**Comment by thijsvdanker** [comment]
I understand that this will not be merged, but @paulrrogers your solution does work, thanks!

**Pull request closed without merging**
