### PR TITLE
Update Laravel Forge instructions.md

### PR DESCRIPTION
**Pull request by mchev**
Installation instructions for Ubuntu 24.04

### CODE REVIEW

**Comment by eriktobben** [comment]
I get the following error on the last step:

```
Note, selecting 'libgcc-s1' instead of 'libgcc1'
E: Unable to locate package libasound2t64
```

**Comment by freekmurze** [comment]
Thanks!

**Comment by sstottelaar** [comment]
> I get the following error on the last step:
> 
> ```
> Note, selecting 'libgcc-s1' instead of 'libgcc1'
> E: Unable to locate package libasound2t64
> ```

I'm also getting this error on the last step.

**Comment by clarkewing** [comment]
@freekmurze just an FYI: I'm not seeing these updated Forge instructions on the [docs site](https://spatie.be/docs/browsershot/v4/requirements). Not quite sure why...

**Pull request merged**
