### PR TITLE
fix disableCaptureURLS

### PR DESCRIPTION
**Pull request by ziaratban**
#861
#869
#871

### CODE REVIEW

**Comment by ziaratban** [comment]
I don't know if this bug is related to the last issue in browsershot or not, but I fixed this bug for BC.

**Comment by freekmurze** [comment]
Could you rebase against main?

**Comment by freekmurze** [comment]
Seems like the tests are failing. Could you maybe rebase against `main` again?

**Comment by freekmurze** [comment]
Seems like there are still some conflicts...

CleanShot 2024-08-26 at 06 51 56@2x

**Comment by ziaratban** [comment]
image
🤔🤔🤔

**Comment by ziaratban** [comment]
is everything ok?

**Comment by AlexVanderbist** [comment]
Hey, thanks for the fix & sorry for the delay

**Pull request merged**
